const expanseData = {
  ExpanseTypes: [
    { name: "Food", id: 1243 },
    { name: "Electricity", id: 345 },
    { name: "Telephone ", id: 346 },
    { name: "Tax", id: 348 },
  ],

  PaymentTypes: [
    { name: "Online", id: 1 },
    { name: "Cash", id: 2 },
    { name: "Google Pay", id: 3 },
  ],

  transactions: [
    {
      id: 1,
      to: "Bill",
      from: "Yash Mehta1",
      typeOfExpanse: "Tex",
      paymentType: "online",
      refNo: 932389,
      amount: 30001,
      notes: "thank you",
      file: "",
      date: "2000-01-01",
    },

    {
      id: 2,
      to: "Bill",
      from: "Yash Mehta2",
      typeOfExpanse: "Food",
      paymentType: "online",
      refNo: 932389,
      amount: 30002,
      notes: "thank you",
      file: "",
      date: "2000-07-21",
    },

    {
      id: 3,
      to: "Bill",
      from: "Yash Mehta3",
      typeOfExpanse: "Electricity",
      paymentType: "online",
      refNo: 932389,
      amount: 80003,
      notes: "thank you",
      file: "",
      date: "2000-06-21",
    },

    {
      id: 4,
      to: "Bill",
      from: "Yash Mehta3",
      typeOfExpanse: "Food",
      paymentType: "online",
      refNo: 932389,
      amount: 20003,
      notes: "thank you",
      file: "",
      date: "2011-05-21",
    },

    {
      id: 5,
      to: "Bill",
      from: "Yash Mehta3",
      typeOfExpanse: "Telephone",
      paymentType: "online",
      refNo: 932389,
      amount: 30003,
      notes: "thank you",
      file: "",
      date: "2000-04-21",
    },

    {
      id: 6,
      to: "Bill",
      from: "Yash Mehta3",
      typeOfExpanse: "Food",
      paymentType: "online",
      refNo: 932389,
      amount: 50003,
      notes: "thank you",
      file: "",
      date: "2000-01-21",
    },

    {
      id: 7,
      to: "Other",
      from: "Sir",
      typeOfExpanse: "Tex",
      paymentType: "online",
      refNo: 932389,
      amount: 30001,
      notes: "thank you",
      file: "",
      date: "2000-03-21",
    },

    {
      id: 8,
      to: "Bill",
      from: "Yash Mehta2",
      typeOfExpanse: "Electricity",
      paymentType: "online",
      refNo: 932389,
      amount: 30002,
      notes: "thank you",
      file: "",
      date: "2000-09-21",
    },

    {
      id: 9,
      to: "Bill",
      from: "Yash Mehta3",
      typeOfExpanse: "Electricity",
      paymentType: "online",
      refNo: 932389,
      amount: 80003,
      notes: "thank you",
      file: "",
      date: "2000-12-21",
    },

    {
      id: 10,
      to: "Bill",
      from: "Yash Mehta3",
      typeOfExpanse: "Food",
      paymentType: "online",
      refNo: 932389,
      amount: 20003,
      notes: "thank you",
      file: "",
      date: "2000-08-21",
    },

    {
      id: 11,
      to: "Bill",
      from: "Yash Mehta3",
      typeOfExpanse: "Telephone",
      paymentType: "online",
      refNo: 932389,
      amount: 30003,
      notes: "thank you",
      file: "",
      date: "2001-05-21",
    },

    {
      id: 12,
      to: "Bill",
      from: "Yash Mehta3",
      typeOfExpanse: "Electricity",
      paymentType: "online",
      refNo: 932389,
      amount: 50003,
      notes: "thank you",
      file: "",
      date: "2000-02-21",
    },

    {
      id: 13,
      to: "Bill",
      from: "Yash Mehta3",
      typeOfExpanse: "Telephone",
      paymentType: "online",
      refNo: 932389,
      amount: 30003,
      notes: "thank you",
      file: "",
      date: "2002-02-25",
    },

    {
      id: 14,
      to: "Bill",
      from: "Yash Mehta3",
      typeOfExpanse: "Food",
      paymentType: "online",
      refNo: 424858,
      amount: 50003,
      notes: "thank you",
      file: "",
      date: "2002-02-21",
    },

    {
      id: 15,
      to: "Bill",
      from: "Yash Mehta3",
      typeOfExpanse: "Telephone",
      paymentType: "online",
      refNo: 932389,
      amount: 30003,
      notes: "thank you",
      file: "",
      date: "2005-02-21",
    },

    {
      id: 16,
      to: "Bill",
      from: "Yash Mehta3",
      typeOfExpanse: "Electricity",
      paymentType: "online",
      refNo: 932389,
      amount: 50003,
      notes: "thank you",
      file: "",
      date: "2006-02-21",
    },

    {
      id: 17,
      to: "Bill",
      from: "Yash Mehta3",
      typeOfExpanse: "Telephone",
      paymentType: "online",
      refNo: 932389,
      amount: 30003,
      notes: "thank you",
      file: "",
      date: "2002-02-25",
    },

    {
      id: 18,
      to: "Bill",
      from: "Yash Mehta3",
      typeOfExpanse: "Food",
      paymentType: "online",
      refNo: 424858,
      amount: 50003,
      notes: "thank you",
      file: "",
      date: "2002-02-21",
    },

    {
      id: 19,
      to: "Bill",
      from: "Yash Mehta3",
      typeOfExpanse: "Telephone",
      paymentType: "online",
      refNo: 932389,
      amount: 30003,
      notes: "thank you",
      file: "",
      date: "2005-02-21",
    },

    {
      id: 20,
      to: "Bill",
      from: "Yash Mehta3",
      typeOfExpanse: "Electricity",
      paymentType: "online",
      refNo: 932389,
      amount: 50003,
      notes: "thank you",
      file: "",
      date: "2006-02-21",
    },

    {
      id: 21,
      to: "Bill",
      from: "Yash Mehta1",
      typeOfExpanse: "Tex",
      paymentType: "online",
      refNo: 932389,
      amount: 30001,
      notes: "thank you",
      file: "",
      date: "2000-01-01",
    },

    {
      id: 22,
      to: "Bill",
      from: "Yash Mehta2",
      typeOfExpanse: "Food",
      paymentType: "online",
      refNo: 932389,
      amount: 30002,
      notes: "thank you",
      file: "",
      date: "2000-02-21",
    },

    {
      id: 23,
      to: "Bill",
      from: "Yash Mehta3",
      typeOfExpanse: "Electricity",
      paymentType: "online",
      refNo: 932389,
      amount: 80003,
      notes: "thank you",
      file: "",
      date: "2008-02-21",
    },

    {
      id: 24,
      to: "Bill",
      from: "Yash Mehta3",
      typeOfExpanse: "Food",
      paymentType: "online",
      refNo: 932389,
      amount: 20003,
      notes: "thank you",
      file: "",
      date: "2003-05-21",
    },

    {
      id: 25,
      to: "Bill",
      from: "Yash Mehta3",
      typeOfExpanse: "Telephone",
      paymentType: "online",
      refNo: 932389,
      amount: 30003,
      notes: "thank you",
      file: "",
      date: "2000-02-21",
    },

    {
      id: 26,
      to: "Bill",
      from: "Yash Mehta3",
      typeOfExpanse: "Food",
      paymentType: "online",
      refNo: 932389,
      amount: 50003,
      notes: "thank you",
      file: "",
      date: "2003-06-21",
    },

    {
      id: 27,
      to: "Other",
      from: "Sir",
      typeOfExpanse: "Tex",
      paymentType: "online",
      refNo: 932389,
      amount: 30001,
      notes: "thank you",
      file: "",
      date: "2000-02-21",
    },

    {
      id: 28,
      to: "Bill",
      from: "Yash Mehta2",
      typeOfExpanse: "Electricity",
      paymentType: "online",
      refNo: 932389,
      amount: 30002,
      notes: "thank you",
      file: "",
      date: "2009-03-21",
    },

    {
      id: 29,
      to: "Bill",
      from: "Yash Mehta3",
      typeOfExpanse: "Electricity",
      paymentType: "online",
      refNo: 932389,
      amount: 80003,
      notes: "thank you",
      file: "",
      date: "2010-12-21",
    },

    {
      id: 30,
      to: "Bill",
      from: "Yash Mehta3",
      typeOfExpanse: "Food",
      paymentType: "online",
      refNo: 932389,
      amount: 20003,
      notes: "thank you",
      file: "",
      date: "2008-08-21",
    },

    {
      id: 31,
      to: "Bill",
      from: "Yash Mehta1",
      typeOfExpanse: "Tex",
      paymentType: "online",
      refNo: 932389,
      amount: 30001,
      notes: "thank you",
      file: "",
      date: "2006-07-01",
    },

    {
      id: 32,
      to: "Bill",
      from: "Yash Mehta2",
      typeOfExpanse: "Food",
      paymentType: "online",
      refNo: 932389,
      amount: 30002,
      notes: "thank you",
      file: "",
      date: "2006-05-21",
    },

    {
      id: 33,
      to: "Bill",
      from: "Yash Mehta3",
      typeOfExpanse: "Electricity",
      paymentType: "online",
      refNo: 932389,
      amount: 80003,
      notes: "thank you",
      file: "",
      date: "2005-02-21",
    },

    {
      id: 34,
      to: "Bill",
      from: "Yash Mehta3",
      typeOfExpanse: "Food",
      paymentType: "online",
      refNo: 932389,
      amount: 20003,
      notes: "thank you",
      file: "",
      date: "2008-02-21",
    },

    {
      id: 35,
      to: "Bill",
      from: "Yash Mehta3",
      typeOfExpanse: "Telephone",
      paymentType: "online",
      refNo: 932389,
      amount: 30003,
      notes: "thank you",
      file: "",
      date: "2002-02-21",
    },

    {
      id: 36,
      to: "Bill",
      from: "Yash Mehta3",
      typeOfExpanse: "Food",
      paymentType: "online",
      refNo: 932389,
      amount: 50003,
      notes: "thank you",
      file: "",
      date: "2004-02-21",
    },

    {
      id: 37,
      to: "Other",
      from: "Sir",
      typeOfExpanse: "Tex",
      paymentType: "online",
      refNo: 932389,
      amount: 30001,
      notes: "thank you",
      file: "",
      date: "2007-02-21",
    },

    {
      id: 38,
      to: "Bill",
      from: "Yash Mehta2",
      typeOfExpanse: "Electricity",
      paymentType: "online",
      refNo: 932389,
      amount: 30002,
      notes: "thank you",
      file: "",
      date: "2006-02-21",
    },

    {
      id: 39,
      to: "Bill",
      from: "Yash Mehta3",
      typeOfExpanse: "Electricity",
      paymentType: "online",
      refNo: 932389,
      amount: 80003,
      notes: "thank you",
      file: "",
      date: "2005-12-21",
    },

    {
      id: 40,
      to: "Bill",
      from: "Yash Mehta3",
      typeOfExpanse: "Food",
      paymentType: "online",
      refNo: 932389,
      amount: 20003,
      notes: "thank you",
      file: "",
      date: "2003-08-21",
    },

    {
      id: 41,
      to: "Bill",
      from: "Yash Mehta1",
      typeOfExpanse: "Tex",
      paymentType: "online",
      refNo: 932389,
      amount: 30001,
      notes: "thank you",
      file: "",
      date: "2004-01-01",
    },

    {
      id: 42,
      to: "Bill",
      from: "Yash Mehta2",
      typeOfExpanse: "Food",
      paymentType: "online",
      refNo: 932389,
      amount: 30002,
      notes: "thank you",
      file: "",
      date: "2003-02-21",
    },

    {
      id: 43,
      to: "Bill",
      from: "Yash Mehta3",
      typeOfExpanse: "Electricity",
      paymentType: "online",
      refNo: 932389,
      amount: 80003,
      notes: "thank you",
      file: "",
      date: "2000-02-21",
    },

    {
      id: 44,
      to: "Bill",
      from: "Yash Mehta3",
      typeOfExpanse: "Food",
      paymentType: "online",
      refNo: 932389,
      amount: 20003,
      notes: "thank you",
      file: "",
      date: "2010-10-29",
    },

    {
      id: 45,
      to: "Bill",
      from: "Yash Mehta3",
      typeOfExpanse: "Telephone",
      paymentType: "online",
      refNo: 932389,
      amount: 30003,
      notes: "thank you",
      file: "",
      date: "2010-05-29",
    },

    {
      id: 46,
      to: "Bill",
      from: "Yash Mehta3",
      typeOfExpanse: "Food",
      paymentType: "online",
      refNo: 932389,
      amount: 50003,
      notes: "thank you",
      file: "",
      date: "2008-11-10",
    },

    {
      id: 47,
      to: "Other",
      from: "Sir",
      typeOfExpanse: "Tex",
      paymentType: "online",
      refNo: 932389,
      amount: 30001,
      notes: "thank you",
      file: "",
      date: "2012-08-01",
    },

    {
      id: 48,
      to: "Bill",
      from: "Yash Mehta2",
      typeOfExpanse: "Electricity",
      paymentType: "online",
      refNo: 932389,
      amount: 30002,
      notes: "thank you",
      file: "",
      date: "2008-02-14",
    },

    {
      id: 49,
      to: "Bill",
      from: "Yash Mehta3",
      typeOfExpanse: "Electricity",
      paymentType: "online",
      refNo: 932389,
      amount: 80003,
      notes: "thank you",
      file: "",
      date: "2008-12-13",
    },

    {
      id: 50,
      to: "Bill",
      from: "Yash Mehta3",
      typeOfExpanse: "Food",
      paymentType: "online",
      refNo: 932389,
      amount: 20003,
      notes: "thank you",
      file: "",
      date: "2010-08-21",
    },
  ],

  reminder: [
    {
      id: 1,
      title: "ligth bill",
      dateOfPayment: new Date(2000, 9, 1),
      amount: 2000,
      repeat: { startDate: new Date(2019, 2, 12), recurringType: "month" }, //start date, type(month)
      reminderBefore: { beforeType: "Day", value: 2}, //day
      notes: "notes",
      done: false,
      hold: false,
      latestExucationDay: new Date(2021, 7, 5),
      snoozeTime: { snoozeType:"Week", value : 5, basetime: new Date() }
    },

    {
      id: 2,
      title: "ligth bill",
      dateOfPayment: new Date(2000, 9, 1),
      amount: 2000,
      repeat: { startDate: new Date(2021, 7, 10), recurringType: "month" }, //start date, type(month)
      reminderBefore: { beforeType: "Day", value: 10}, //day
      notes: "notes",
      done: false,
      hold: false,
      latestExucationDay: new Date(2021, 6, 30),
      snoozeTime: { snoozeType:"Week", value : 5, basetime: new Date() }
    },

    {   

      id: 3,
      title: "ligth bill",
      dateOfPayment: new Date(2000, 9, 1),
      amount: 2000,
      repeat: { startDate: new Date(2019, 2, 12), recurringType: "month" }, //start date, type(month)
      reminderBefore: { beforeType: "Day", value: 2}, //day
      notes: "notes",
      done: false,
      hold: false,
      latestExucationDay: new Date(2021, 3, 12),
      snoozeTime: { snoozeType:"Week", value : 5, basetime: new Date() }
    },
  ],
};

export default expanseData;
